### ISSUE TITLE
Separation of concerns

### ISSUE THREAD

**Issue by henriquebastos** [rca/django-resourceful#1]
Interesting package @rca! Tks for sharing.

This is less an "issue" and more a discussion to get your opinion on something I've been thinking.

_django-resourceful_ does 3 things:
1. Generates the urls
2. Implements default views
3. Suplies a dispatch workflow

As all those 3 things are very connected to each other, they're all implemented on a single class. On the other hand, Django already has many conventions related to CBGV.
- Have you tried to use CBGV with django-resourceful?
- Do you think it would made sense for this project to separate these 3 concerns (url mapper, dispatch and views)?

I'll experiment on those ideas to share some actual code. But if you have any thoughts to share I would be glad to hear.

**Comment by rca** [comment]
Hey, thanks for the comments!  I started this project as a way to wrap my head around resources and API endpoints.  I was unhappy with the Django API packages I had tried out at the time.

Lately I've been using Django REST Framework (http://www.django-rest-framework.org/) and I believe it provides the separation you're looking for.  It's also is one of the most used API frameworks built on top of Django and the author is looking for help to make massive improvements in the near future: https://www.kickstarter.com/projects/tomchristie/django-rest-framework-3

I would say give DRF a good look and come back to this project if it does not satisfy your needs.

Thanks again!
-Roberto.

**Comment by henriquebastos** [comment]
Yes, I use DRF too. It's great.

Now I understand your design decisions. You were prioritizing APIs. Nice.

I'm more interested on the web part of the system. I've also found interesting projects that consider this:
- [djangny](http://zacharyvoase.github.io/dagny/uris)
- [django-viewsets](https://github.com/BertrandBordage/django-viewsets)

Thank you for your reply. When I find the time to experiment with those 3 projects, I can share new thoughts with you.

All the best!

**Comment by luzfcb** [comment]
another project using a similar url pattern:

http://amitu.com/smarturls/
https://github.com/amitu/smarturls

**Comment by rca** [comment]
Wow, looking back here is like a time capsule.  😀

Thank you for the comments and discussion here.
