### ISSUE TITLE
Error installing the package

### ISSUE THREAD

**Issue by jsteerv** [rca/django-resourceful#2]
Hi i'm newbie on python. I tryed to install this packages in both ways:

pip install -r requirements.txt
 (# with -e git://github.com/rca/django-resourceful.git#egg=django-resourceful)

and

pip install -e git://github.com/rca/django-resourceful.git#egg=django-resourceful

and it says everytime: 
Obtaining django-resourceful from git+git://github.com/rca/django-resourceful.gi
t#egg=django-resourceful (from -r requirements.txt (line 1))
  Cloning git://github.com/rca/django-resourceful.git to c:\wamp\www\django\asis
tant\src\django-resourceful
Installing collected packages: django-resourceful
  Running setup.py develop for django-resourceful
Successfully installed django-resourceful-0.2

But the package doesnt get installed. I tryed to install it manually by:
src\django-resourceful> python setup.py install

But it shows this error: 

byte-compiling C:\Program Files (x86)\Python 3.5\Lib\site-packages\resourceful\v
iews.py to views.cpython-35.pyc
  File "C:\Program Files (x86)\Python 3.5\Lib\site-packages\resourceful\views.py
", line 247
    except Exception, exc:
                    ^
SyntaxError: invalid syntax

byte-compiling C:\Program Files (x86)\Python 3.5\Lib\site-packages\resourceful_
_init__.py to **init**.cpython-35.pyc
running install_egg_info
Writing C:\Program Files (x86)\Python 3.5\Lib\site-packages\django_resourceful-0
.2-py3.5.egg-info

I already installed the flexmock==0.9.7 andnose==1.3.0... i'm lost. What can i do? 
By the way, i am using windows 7 64 bits, python 3.5 and Django 1.8.5

Thanks in advance!

**Comment by rca** [comment]
Super old issue, sorry 😒

FWIW, seems to install just fine; my guess for this issue is that it was a `pip` bug.  🤷🏽‍♂️

```
$ pip --version
pip 19.3 from /Users/berto/.local/share/virtualenvs/django-resourceful-ytX9VHq5/lib/python2.7/site-packages/pip (python 2.7)
$ pip install -e git://github.com/rca/django-resourceful.git#egg=django-resourceful
Obtaining django-resourceful from git+git://github.com/rca/django-resourceful.git#egg=django-resourceful
[...]
Successfully installed django-resourceful
$ python
[...]
>>> import resourceful
>>> resourceful
<module 'resourceful' from '/Users/berto/.local/share/virtualenvs/django-resourceful-ytX9VHq5/src/django-resourceful/resourceful/__init__.py'>
```
