### ISSUE TITLE
Code without License

### ISSUE THREAD

**Issue by portela** [rca/django-resourceful#3]
Dear Roberto,

django-resourceful is a very interesting project. I really like it and I think it has a tremendous potential. 

We all know there are others solutions out there, like DRF; but I think the approach you took is unique and believe there is still a niche for it. 

 I really would like to test it, and, maybe even improve it; but your code has no license with it (which means it is not open-source). Using a code without a license is a huge liability for people and corporations. You can read more about it at [https://choosealicense.com/licenses/mit/](https://choosealicense.com/no-permission/).

So, I kindly ask you to add an open-source, and permissive, license to you. Such an awesome code should be shared!! 

May I suggest a MIT LICENSE ([https://choosealicense.com/licenses/mit/](https://choosealicense.com/licenses/mit/))?

Sincerely,
Henrique Portela

P.S.: I was going to add the license and submit a pull request to save you the trouble (so you would only have to merge it), but I realize that I cannot do that without breaking copyright. So, I decide to only open an issue.

**Comment by rca** [comment]
Hello!

Apologies for missing this.  I tend to add the Apache license to projects.  It is pretty close to the MIT [with a couple more attributes](https://choosealicense.com/licenses/apache-2.0/).  I will add the license and push in a minute; that should free you up to use in open source and commercial applications.

Cheers!
-Roberto.

![Screen Shot 2019-10-16 at 7 44 31 AM](https://user-images.githubusercontent.com/53537/66916241-d49cae80-efe8-11e9-8096-112662af795c.png)
